### ISSUE TITLE
Error with patch 1.4.1.0

### ISSUE THREAD

**Issue by jhomer** [Xentro/FS19-AddSpecialization#2]
I was having specialization errors with a mod I made after patch 1.4.0.0 and 1.4.1.0
I also tried adding in your FS-AddSpecialization to replace what I had in the mod but was still having errors.

I also tried your FS-AddSpecialization just as a standalone just to make sure it wasn't with my mod but still had errors.
Not sure what Giants did with the new patches?

`2022-04-21 08:13   Load mod: FS_AddSpecialization_FS_22
2022-04-21 08:13   Error: Invalid customEnvironment given for SpecializationManager.addSpecialization. Should be a string or nil.
2022-04-21 08:13 LUA call stack:
  dataS/scripts/mods.lua (396) : printCallstack
  =C:/Users/James.000/Documents/My Games/FarmingSimulator2022/mods/FS_AddSpecialization_FS_22/scripts/AddSpecialization.lua (232) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (347) : source
  dataS/scripts/mods.lua (839) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (836) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1152) : update
2022-04-21 08:13   Error: Too many arguments for SpecializationManager.addSpecialization. (Arguments should be: name, className, filename, customEnvironment)
2022-04-21 08:13 LUA call stack:
  dataS/scripts/mods.lua (401) : printCallstack
  =C:/Users/James.000/Documents/My Games/FarmingSimulator2022/mods/FS_AddSpecialization_FS_22/scripts/AddSpecialization.lua (232) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (347) : source
  dataS/scripts/mods.lua (839) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (836) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1152) : update
2022-04-21 08:13 Add Specialization ( SampleSpecialization ) - Info: We have successfully added specialization Into ( 31 / 140) of the vehicleTypes.`

**Comment by Xentro** [comment]
From my testing its working now.
